create table if not exists public.journal_daily_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  sentiment_today text,
  view_outcome text,
  previous_day_market text,
  observations text,
  notes text,
  motivation_quote text,
  market_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entry_date)
);

create or replace function public.set_journal_daily_entries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists journal_daily_entries_set_updated_at on public.journal_daily_entries;

create trigger journal_daily_entries_set_updated_at
before update on public.journal_daily_entries
for each row
execute function public.set_journal_daily_entries_updated_at();

alter table public.journal_daily_entries enable row level security;

drop policy if exists journal_daily_entries_select_own on public.journal_daily_entries;
create policy journal_daily_entries_select_own
on public.journal_daily_entries
for select
using (auth.uid() = user_id);

drop policy if exists journal_daily_entries_insert_own on public.journal_daily_entries;
create policy journal_daily_entries_insert_own
on public.journal_daily_entries
for insert
with check (auth.uid() = user_id);

drop policy if exists journal_daily_entries_update_own on public.journal_daily_entries;
create policy journal_daily_entries_update_own
on public.journal_daily_entries
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists journal_daily_entries_delete_own on public.journal_daily_entries;
create policy journal_daily_entries_delete_own
on public.journal_daily_entries
for delete
using (auth.uid() = user_id);
